# Generated by Django 5.0.6 on 2024-07-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'easy'), ('MEDIUM', 'medium'), ('HARD', 'hard')], default='MEDIUM'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=125)),
                ('description', models.TextField()),
                ('seq_no', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('EASY', 'easy'), ('MEDIUM', 'medium'), ('HARD', 'hard')], default='MEDIUM')),
                ('length', models.CharField(choices=[('SHORT', 'short'), ('MEDIUM', 'medium'), ('LONG', 'long')], default='MEDIUM')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
